version: '3.8'

services:
  test-php84:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PHP_VERSION: "8.4"
    volumes:
      - .:/app
    depends_on:
      - db-test
    environment:
      - DATABASE_URL=mysql://root:secret@db-test/test_openapi_theme?encoding=utf8mb4&timezone=UTC&cacheMetadata=true

  test-php83:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PHP_VERSION: "8.3"
    volumes:
      - .:/app
    depends_on:
      - db-test
    environment:
      - DATABASE_URL=mysql://root:secret@db-test/test_openapi_theme?encoding=utf8mb4&timezone=UTC&cacheMetadata=true

  db-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_openapi_theme
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306" 